config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/register', to: 'users#create'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :completion_dates
  resources :tasks
  resources :plants
  resources :gardens
  resources :users
  get '/settings', to: "users#settings", as: "settings"
  root 'newleaf#landing'

  
  get '/home', to: 'users#home'
  # get 'garden', to: 'gardens#garden'

  # get 'garden', to: 'gardens#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/completion_date.rb
class CompletionDate < ApplicationRecord
  belongs_to :task
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :user
  has_many :plants, dependent: :destroy
  accepts_nested_attributes_for :plants

  def plant_population
   
    self.plants.count
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :tasks, dependent: :destroy
  has_many :users, through: :tasks
  has_many :users, through: :garden

  validates :plant_type, :size, :water_ammount, presence: true
  

  # t.string "plant_type"
  # t.string "nickname"
  # t.integer "size"
  # t.integer "water_ammount"

  def plant_tasks
    self.tasks.count
  end

  def plant=(input)
    byebug
  end


end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :plant
  belongs_to :user
  has_many :gardens, through: :user

  validates :name, :plant_id, :user_id, presence: :true

  def complete
    self.update(updated_at: Time.now)
  end

  def interval_days
    case self.interval
    when "daily"
      # change to 1.day
      # change for test to 5 seconds to show the red lines
      5.second
    when "weekly"
      7.day
    when "bi-weekly"
      14.day
    when "monthly"
      1.month
    end
  end

  def time_left
    if weeks < 1
      if days < 1
        if hours < 1
          if minutes < 1
            if seconds < 1
               return "Overdue."
            else
              "#{seconds} second#{"s" if seconds > 1}"
            end
          else
            "#{minutes} minute#{"s" if minutes > 1}"
          end
        else
          "#{hours} hour#{"s" if hours > 1}"
        end
      else
        "#{days} day#{"s" if days > 1}"
      end
    else
      "#{weeks} week#{"s" if weeks > 1}"
    end
  end

  def weeks
    (((self.updated_at + interval_days) - Time.now)/604800).floor
  end

  def days
    (((self.updated_at + interval_days) - Time.now)/86400).floor
  end

  def hours
    (((self.updated_at + interval_days) - Time.now)/3600).floor
  end

  def minutes
    (((self.updated_at + interval_days) - Time.now)/60).floor
  end
  
  def seconds
    (((self.updated_at + interval_days) - Time.now)).floor
  end


end

app/models/user.rb
class User < ApplicationRecord
    # has_many :plants, dependent: :destroy
    has_many :tasks, dependent: :destroy
    has_one :garden, dependent: :destroy
    has_many :plants, through: :garden
    has_many :plants, through: :tasks
    validates :username, uniqueness: true, presence: true
    validates :password, presence: true
    
    has_secure_password

    def garden_name=(param)
    
        self.garden = Garden.create(garden_name: param['garden_name'], user_id: self.id)
    end

    def self.other_users(userCurrent)
        # return an array where the current user is not in it
        
        self.all.select do |user|
            user.id != userCurrent.id
        end
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorize 
    helper_method :current_user
    protect_from_forgery with: :null_session

    def current_user
        User.find_by(id: session[:user_id])
    end

    def current_plant
        Plant.find_by(id: session[:plant_id])
    end

    def login_user(user)
        session[:user_id] = user.id
    end

    def logged_in?
        !!current_user
    end

    def authorize
        unless logged_in?
            flash[:notice] = "You must be logged in to see this page"
            redirect_to login_path
        end
    end

end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController

    def index

        @garden = Garden.find_by(user_id: current_user.id)
       
    end

    def show
        @garden = Garden.find_by(user_id: params[:id])
    end

    private

    def garden_params
        # waterammount <<< new spelling
        # needs to have nested attributes for plant
        params.require(:garden).permit(:garden_name,:plant_pop)
    end
  

end

app/controllers/newleaf_controller.rb
class NewleafController < ApplicationController
    skip_before_action :authorize, only: [:landing]
    
    def landing
    end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    before_action :find_plant, only: [:show, :edit, :update, :destroy]
    def new
        @plant = Plant.new
        
    end

    def show
        @task = Task.new
    end

    def create
        @plant = Plant.new(plant_params)
        if @plant.save
            redirect_to gardens_path
        else
            render :new
        end
    end

    def destroy
        # find current plant
       
        @plant.destroy
        # remove current plant 
       
        redirect_to gardens_path
        # redirect to currentusers garden
    end
    
    private

    def find_plant
        @plant = Plant.find(params[:id])
    end
    
    def plant_params
        params.require(:plant).permit(:plant_type, :nickname, :size, :water_ammount, :garden_id)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]
  def new
  end

  def create
   @user = find_user
    if @user && @user.authenticate(params[:password])
        login_user(@user)
        flash[:notice] = "Login succesfull! Welcome #{@user.username}"
        redirect_to gardens_path(current_user)
    else 
      flash[:notice] = "Incorrect username or password"
      redirect_to login_path 
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "Logged out!"
    redirect_to login_path
  end

  private
  def find_user
    User.find_by(username: params[:username])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
    def new
        @task = Task.new
    end

    def create
        @task = Task.new(task_params)
        @task.interval = params[:interval]
        if @task.save
            # redierct to plant page belonging to the garden
            redirect_to @task.plant
        else
            render :new
        end
        
    end

    def show
        @task = Task.find(params[:id])
    end

    def destroy
        @task = Task.find(params[:id])
          @task.delete  
        redirect_to @task.plant
    end

    def update
        @task = Task.find(params[:id])
        @task.complete
        redirect_to @task.plant
    end

    private
    def task_params

        params.require(:task).permit(:name, :interval, :plant_id, :user_id)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create]
  def index
    @users = User.other_users(current_user)

  end
  def home
  end

  def show
    #find_user
    render :show
  end

  def edit
    #find_user
    render :edit
  end

  def new
    @user = User.new
    @errors = flash[:errors]
    render :new
  end
    
  def create
    @user = User.new(user_params)
      if @user.save
        login_user(@user)
        redirect_to gardens_path(current_user)

      else 
        flash[:errors] = @user.errors.full_messages
        redirect_to new_user_path
    end
  end

  def settings

  end

  def update
    password = params[:password]
    @user = User.update(user_params)
    redirect_to gardens_path
  end

  def destroy
    @user.destroy
    redirect_to new_user_path
  end
  
  private
    
  def user_params
    params.require(:user).permit(:username, :password,:password_confirmation, garden_name:[:garden_name])
  end
  
  def find_user
   @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completion_dates_helper.rb
module CompletionDatesHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gardens/create.html.erb
<h1>No Garden?</h1>

app/views/gardens/index.html.erb
  <section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="hero title">
      <h2 class="hero subtitle">
        Garden Name:  <%= @garden.garden_name %>
        <h1 class="hero title">
        <h2 class="hero subtitle">
        Garden Owner:  <%= @garden.user.username %>
        <h1 class="hero title">
        <h2 class="hero subtitle">
        Current Plant Population:  <%= @garden.plant_population %></h1>
        <h1 class="hero title">
        <h2 class="hero subtitle">
        <div class="headerNav">
          <span>Plant a seed: <%=button_to "🌱",new_plant_path, method: :get, class: "button is-link"%></span>
        </div>  
        <br>
        Add Some Plants!
        <hr>
         🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🐢🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀
       
      </h2>
    </div>
  </div>
</section>

<div>
<div class="d-flex justify-content-center flex-wrap">
    <% @garden.plants.each do |p|%>
      <div class="task-btn w-auto">
          <div class="col btn task btn-outline-success">
              <a href="/plants/<%="#{p.id}"%>" class="btn btn-custom">
                🌱<br>
                <span><small>Nickname:</small></span>
                <small><b><%= p.nickname.capitalize%></b></small><br>
                <hr>
                <span><small>Plant Type:</small></span>
                <small><i><%= p.plant_type.capitalize %></i></small>  
              </a><br>

              <%= link_to "🗑", p, method: :delete, class: "trash"%>
          </div>
        </div>
      
    <% end %>
</div>

app/views/gardens/new.html.erb
<h1>New Garden?</h1>

app/views/gardens/show.erb
 </div>
  <section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="hero title">
      <h2 class="hero subtitle">
        Garden Name:  <%= @garden.garden_name %>
        <h1 class="hero title">
        <h2 class="hero subtitle">
        Garden Owner:  <%= @garden.user.username %>
        <h1 class="hero title">
        <h2 class="hero subtitle">
        Current Plant Population:  <%= @garden.plant_population %></h1>
        <hr>
        🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🐢🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳🌱🌿🍃🍀🌳
  </div>
</section>


<div class="d-flex justify-content-center flex-wrap">
    <% @garden.plants.each do |p|%>
      <div class="task-btn w-auto">
          <div class="col btn task btn-outline-success">
              <a  class="btn btn-custom">
                🌱<br>
                <span><small>Nickname:</small></span>
                <small><b><%= p.nickname.capitalize%></b></small><br>
                <hr>
                <span><small>Plant Type:</small></span>
                <small><i><%= p.plant_type.capitalize %></i></small>  
              </a><br>
          </div>
        </div>
      
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <title>LeafOut</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <i class="fa fa-download" aria-hidden="true"></i>
  </head>

  <body>
  
    <div>
    <%= current_user ? (render partial: "layouts/nav/logged_in2") : (render partial: "layouts/nav/logged_out2")   %>
    </div>
    

    <%= yield %>

        <%# <div class="bg-img">
          <%= (image_tag "home/original.jpg") unless current_page?(gardens_path) || current_page?(new_plant_path) %>
        
        </div> 

          <%# <div class="bg-img">
          <%= (image_tag "home/original.jpg") unless current_page?(gardens_path) || current_page?(new_plant_path) %>
      </div> 
  </body>
  
  <footer class="hero footer is-success">
    <hr>
    <div class="hero footer-bottom has-text-centered is-success">
      <span>© 2020 <a href="">Leaf-Out</a> A <a href="https://flatironschool.com/">Flatiron School</a> Project By Francisco and Netaly.</span>
      <div class="tile is-parent">
      <article class="tile is-child notification is-danger">
        
        <span><h6>MADE WITH  <span class="glyphicon glyphicon-heart"></span> BY NETALY & FRANCISCO</h6></span>
        <div class="content">
          <!-- Content -->
        </div>
      </article>
    </div>
    </div>
  </div>
</footer>
</html>

app/views/layouts/nav/_logged_in.html.erb
<%# view buttons for garden=> users plants, log out, "settings", users home%>
<!DOCTYPE html>
 <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">

    <header>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" > <%= image_tag "home/KOMOREBI.png", size: "60x60" %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/plants/new">Seed <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href=<%= gardens_path(current_user) %>> Garden</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users">Homies</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <button type="button" class="btn btn-outline-warning"><%= link_to "Settings", settings_path, method: :get %></button>
            <button type="button" class="btn btn-outline-success"><%= link_to "Log Out", logout_path, method: :delete %></button>
          </form>
        </div>
      </nav>
    </header>

app/views/layouts/nav/_logged_in2.html.erb
<nav id="navbar" class="bd-navbar navbar has-shadow is-success">
  <div class="container">
  <div class="navbar-menu">
    <a class="navbar-item" >
          <h4><strong>Komorebi</strong></h4> 
    </a>
  </div>  
   
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link" href="/home">
          More
        </a>
        <div id="moreDropdown" class="navbar-dropdown">
          <a class="navbar-item is-hidden-widescreen" href="https://github.com/jgthms/bulma" target="_blank">
          </a>
          <hr class="navbar-divider is-hidden-widescreen">
            </a>
            <a class="navbar-item  " href="/users">
              <span>
                <strong>Users</strong>
                <br>
                View all the users
              </span>
            </a>
              <hr class="navbar-divider ">
            <a class="navbar-item  " href="/gardens">
              <span>
                <strong>Garden</strong>
                <br>
                Visit "<%= current_user.garden.garden_name  %>".
              </span>
            </a>
              <hr class="navbar-divider ">
            <a class="navbar-item  " href="/plants/new">
              <span>
                <strong>Seed</strong>
                <br>
                Plant a seed form.
              </span>
            </a>
              <hr class="navbar-divider ">
            <a class="navbar-item  " href="/settings">
              <span>
                <strong>Settings</strong>
                <br>
                User Settings
              </span>
            </a>
              <hr class="navbar-divider ">
            <a class="navbar-item  " href="/rails/info">
              <span>
                <span class="icon has-text-success">
                </span>
                <strong>PATHS</strong>
                <br>
              </span>
              </a>
              </div>
            </div>
          </div>
           <a class="button is-success"> User: <%= current_user.username %></a>
          <button type="button" class="button is-success"><%= link_to "Log Out", logout_path, method: :delete %></button>

          <div class="navbar-end">
          </p>
          </p>
        </div>
      </div>
    </div>
  </div>
  </div>
</nav>

app/views/layouts/nav/_logged_out.html.erb
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href='/' >🌱Komorebi🌱</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
           
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            
            <button type="button" class="btn btn-outline-success my-2 my-sm-0"><%= link_to "Sign Up", '/users/new', method: :get%></button>
            <button type="button" class="btn btn-outline-success my-2 my-sm-0"><%= link_to "Log in", '/login', method: :get%></button>
          </form>
        </div>
      </nav>

app/views/layouts/nav/_logged_out2.html.erb
<nav id="navbar" class="bd-navbar navbar has-shadow is-spaced">
  <div class="container">
  <div class="navbar-menu">
    <a class="navbar-item" >
          <h4><strong>Komorebi</strong></h4> 
    </a>
  </div>
      
          <a class="button is-success" style="height: 2.25em; padding: calc(.375em - 1px) .75em;" href="/users/new">
              <strong>Register</strong>
            </a>
          <a class="button is-success" style="height: 2.25em; padding: calc(.375em - 1px) .75em;" href="/login">
              <strong>Login</strong>
            </a>
          <div class="navbar-end">
          </p>
          </p>
        </div>
      </div>
    </div>
  </div>
  </div>
</nav>

app/views/newleaf/landing.html.erb
<%# create button for login/ signup/ show some gardens%>
<%# <%= button_to  "LogIn", login_path, method: :get%>

app/views/plants/index.html.erb
<%= @info %>
   

app/views/plants/new.html.erb
<% if @plant.errors.any?  %>
    <% @plant.errors.full_messages.each do |m| %>
        <div class="notification is-success is-light">
  <button class="delete"></button>
  <%=  m %>
</div>
    <% end %>
<% end %>
</div>



<div class= "form text-center" >
<br>
<%= form_for @plant do |f| %>
    <%= f.hidden_field :garden_id, value: "#{current_user.garden.id}" %>
    <div class="form-group">
        <%= f.label :plant%>
        <%= f.text_field :plant_type, class: "form-control" %> 
    </div>
    <div class="form-group">
        <%= f.label :nickname%>
        <%= f.text_field :nickname, class: "form-control" %> 
    </div>
    <div class="form-group">
        <%= f.label :size_in_inches%>
        <%= f.number_field :size, class: "form-control", placeholder: "inch" %>
    </div>

    <div class="form-group">
        <%= f.label :amount_of_water%>
        <%= f.number_field :water_ammount, class: "form-control", placeholder: "cup"%> 
    </div>
    <br>
    <%= f.submit "Plant Seed", class: "btn btn-outline-info"%>
<% end %>
<br>
</div>

app/views/plants/show.html.erb
<div class=" d-flex justify-content-between border">
    <div class="d-flex flex-column plant-data">
       <table class="table-bordered" >
            <tr>
                <th scope="row">Nickname: </th>
                <td> <%= @plant.nickname %></td>
            </tr>
            <tr>
                <th>Plant Type: </th>
                <td><%= @plant.plant_type %></td>
            </tr>
            <tr>
                <th >Size: </th>
                <td><%= @plant.size %></td>
            </tr>
            <tr>
                <th id="care"> Care:
               
                <p id="care-attr"> *water amount</p>
                </th>
                <td><%= pluralize(@plant.water_ammount, "cup") %></td> 
            </tr>
       </table>
    </div>

    <div class="d-flex flex-column w-100 task-box-container ml-5">

        <div class="d-flex justify-content-between new-task mr-4"> 
          <div>
            <%= link_to "<=", gardens_path, method: :get, class: "btn btn-outline-info mt-3 new-task-btn" %>
          </div>
            <% if @plant.tasks.count == 0 %>
                
                    <h1 class="alert alert-success" role="alert"> Add A Task To Get Started!</h1>
              
            <% end %>

                <div>
                <%= link_to "+", new_task_path(plant_id: @plant.id), class: "btn btn-outline-info mt-3 new-task-btn"%>
                </div>


<%#  %>

 <%#  %>
        </div>

            <div class="d-flex justify-content-start flex-wrap">
            
                <% @plant.tasks.reverse.each do |task|%>
                    <div class="task-btn w-auto">
                        <div class="col btn task btn-outline-info <%= "overdue-btn" if task.time_left == "Overdue." %>" >
                        <h5>Task:</h5>
                            <%= link_to task.name, task, method: :patch, class: "task-name" %>
                            <hr id="taskline">
                            
                            <span><small>Frequency:</small></span>
                            <small><%= task.interval %><br></small>
                            <span><small>Time Left:</small></span>
                            <small><%= task.time_left %></small>
                            <%= button_to  "🗑", task, method: :delete, class: "trash"%>
                        
                        </div>
                    </div>
                <% end %>
            </div>
    </div>


</div>

app/views/tasks/new.html.erb
<div class="text-center">
        <div style="margin: 0 30em;">
                <% if @task.errors.any? %>
                        <% @task.errors.full_messages.each do |m|%>
                                <div class="notification is-info is-light" style="padding: 0.3em 2em; margin-bottom: 1em;">
                                <button class="delete"></button>
                                <%= m %><br>
                                </div>
                        <% end%>
                <% end%>
        </div>

        <div class="text-center form">
        <br>
                <h1>New Task</h1>
                <hr>
                <%= form_with model: @task, local: true do |f|%>
                
                <div class="form-group text-center" style="margin: 0 3em;" >
                        <%= f.label :name %>
                        <%= f.text_field :name, class: "form-control"%><br>
                </div>

                <div class="form-group" style="margin: 0 3em;" >
                        <%= f.label :interval %>
                        <select name="interval" class="form-control">
                                <option value=daily>Daily</option>
                                <option value=weekly>Weekly</option>
                                <option value=bi-weekly>Bi-Weekly</option>
                                <option value=monthly>Monthly</option>
                        </select><br>
                </div>

                        <%= f.hidden_field :user_id, value: current_user.id %>
                        <%= f.hidden_field :plant_id, value: params[:plant_id] %>
                
                        <%= f.submit class: 'btn btn-outline-info' %>
                
                <% end %>
                        <br>
        </div>
</div> 

app/views/tasks/show.erb
<section class="hero is-link">
  <div class="hero-body">
    <div class="container">
      <h1 class="hero title">
      <h2 class="hero subtitle">
        Tasks: <%=  %> 
        </h1>
      </h2>
    </div>
  </div>
</section>

app/views/users/create.erb
<h1> CREATE NEW USER </h1>

<%= render "form" %>

app/views/users/edit.erb
<div class=" text-center form">

<h1> Edit Profile </h1>
  <%= form_for @user do |f| %>

    <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <%= f.fields_for :garden_name do |g| %>
    <div class="form-group">
        <%= g.label :garden_name %>
        <%= g.text_field :garden_name, class: "form-control"  %> 
    </div> 

      <% end %>
    <br>
    <%= f.submit class: 'btn btn-outline-info'%>
    <% end%>
</div>

app/views/users/home2.erb
   <!-- Header -->
  <section class="hero is-link is-fullheight is-fullheight-with-navbar">
    <div class="hero-body">
      <div class="container">Welcome to
        <h1 class="title is-1">
          Komorebi
        </h1>
        <h2 class="subtitle is-3">
          a plant catalogue & care web application.
      </h2>
        <%= yield %>
      </div>
    </div>
  </section>

app/views/users/index.erb
  <div>
    <section class="hero hero-body is-success">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          🌱Homies🌱
        </h1>
        </h2>
      </div>
    </div>
  </section>
<br>
  <div class="d-flex justify-content-between">
         </h1>
        
          <br>
          <% @users.each do |user| %>
          <h1 class="subtitle">
          
                <div class="card" style="width: 18rem;">
                <img alt="Plant | Plant doodle, Motion graphics gif, Animation design" class="n3VNCb" src="https://i.pinimg.com/originals/e8/88/d4/e888d4feff8fd5ff63a965471a94b874.gif" data-noaft="1" jsname="HiaYvf" jsaction="load:XAeZkd,gvK6lb;" style="width: 400px; height: 300px; margin: 0px;" class="card-img-top">
                <div class="card-body">
                  <p class="card-text">Gardener Username: <br>
                  <%= link_to user.username, garden_path(user) %></p>
                </div>
              </div>
         
          </h1>
          <% end%>
          <br>
        </h2>
  </div>






</div>

app/views/users/new.erb
<br>


<% if @errors%>
    <% @errors.each do |err| %>
        
  <div class="notification is-link is-light">
  <button class="delete"></button>
  <%= err%>
</div>

    <% end%>
<% end%>

<%= render "form" %>

app/views/users/settings.erb
  <section class="hero hero-body  is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Settings
      </h1>
      <h2 class="subtitle">
        <br>
        <%= link_to "Edit User", edit_user_path(current_user)%>
        <br>
        <%= link_to "Delete Profile", user_path(current_user), method: 'delete', data: {confirm: "Are you sure?"} %>
        <br>
      </h2>
    </div>
  </div>
</section>

app/views/users/settings.html.erb
<h1>welcome <%= link_to @user.username, @user %></h1>
<br>
#TODO: add a link to garden
garden name:<%# garden name: <%=  %> %>

<%= if current_user.id == @user.id
button_to "Edit", edit_user_path(@user) , method: :get 
end%>
<%= if current_user.id == @user.id
button_to "Delete", edit_user_path(@user) , method: :get 
end%>

app/views/users/show.erb
<br>
<h1>User Profile<%= link_to @user.username, @user %></h1>
<br>
<%= if current_user.id == @user.id
button_to "Edit", edit_user_path(@user) , method: :get 
end%>
<%= if current_user.id == @user.id
button_to "Delete", edit_user_path(@user) , method: :get 
end%>